# Generated by Django 5.0.6 on 2024-07-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_likes_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
