# Generated by Django 5.0.6 on 2024-07-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_comment_options_alter_post_options_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=models.CharField(max_length=150), max_length=250
            ),
        ),
    ]
